In [3]:
# importing libraries

In [42]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split

In [6]:
df=pd.read_csv('Telco-Customer-Churn.csv')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [8]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [9]:
df.describe()

SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [10]:
# we can see that the ID column is not revelant, so we will remove that column from the dataset.


In [12]:
df.drop(['customerID'], axis=1, inplace=True)


In [13]:
# Now getting dummy values for the columns which require them for further analysis.

In [14]:
df = pd.get_dummies(df, columns = ['gender', 'Partner',   'Dependents','PhoneService',
                                   'MultipleLines','InternetService','OnlineSecurity',
                                   'OnlineBackup','DeviceProtection','TechSupport','StreamingTV',
                                   'StreamingMovies','Contract','PaperlessBilling','PaymentMethod','Churn'], 
                    drop_first = True)

In [15]:
# Converting TotalCharges column from object type to float type, which will help in calculations

In [16]:
df['TotalCharges'] = pd.to_numeric(df.TotalCharges, errors = 'coerce')
df.drop(['TotalCharges'], axis = 1, inplace = True)

In [17]:
# Now splitting the dataset into train and test samples.

In [19]:
df['Churn_Yes'] = df['Churn_Yes'].astype(int)

Y = df['Churn_Yes'].values
X = df.drop(labels = ['Churn_Yes'],axis = 1)


# Create Train & Test Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [20]:
# Now time to use different ML Algorithms.

In [21]:
# 1. Logistic Regression.

In [24]:
from sklearn.linear_model import LogisticRegression


model = LogisticRegression()
result = model.fit(X_train, y_train)

C:\Users\harsh\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [37]:
from sklearn import metrics

prediction_test = model.predict(X_test)

# Print the prediction accuracy
print (metrics.accuracy_score(y_test, prediction_test))

0.8211497515968772


In [38]:
confusion_matrix(y_test, prediction_test)

array([[939,  97],
       [155, 218]], dtype=int64)

In [39]:
precision_score(y_test, prediction_test)

0.692063492063492

In [43]:

accuracy_score(y_test, prediction_test)

0.8211497515968772

In [26]:
# This shows that our predictions using Logistic Regerssion are 82% correct.


In [28]:
#  2.  KNN -  K Nearest Neighbor

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
knn=KNeighborsClassifier()
knn.fit(X_train, y_train)

y_pred_knn= knn.predict(X_test)


In [31]:
# Print the prediction accuracy
print (metrics.accuracy_score(y_test, y_pred_knn))

0.7721788502484032


In [33]:
from sklearn.metrics import confusion_matrix, precision_score

In [35]:
confusion_matrix(y_test, y_pred_knn)

array([[894, 142],
       [179, 194]], dtype=int64)

In [36]:
precision_score(y_test, y_pred_knn)

0.5773809523809523

In [44]:
accuracy_score(y_test, y_pred_knn)

0.7721788502484032

In [45]:
# Here KNN gives us the acuuray of 77%

In [46]:
# Random Forest Algorithm.

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
rf= RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [49]:
y_pred_forest= rf.predict(X_test)

In [50]:
confusion_matrix(y_test, y_pred_forest)

array([[948,  88],
       [203, 170]], dtype=int64)

In [51]:
precision_score(y_test, y_pred_forest)

0.6589147286821705

In [52]:
accuracy_score(y_test, y_pred_forest)

0.7934705464868701

In [53]:
# Random Forest Algorithm gives us the accuracy of 79%


In [54]:
# Conclusion.

In [58]:
print('The accuracy of Logistic Regression Algorithm is:' , accuracy_score(y_test,prediction_test)*100, '%')
print('The accuracy of K Nearest Neighbor Algorithm is:' , accuracy_score(y_test,y_pred_knn)*100, '%')
print('The accuracy of Random Forest Algorithm is:' , accuracy_score(y_test,y_pred_forest)*100, '%')

The accuracy of Logistic Regression Algorithm is: 82.11497515968772 %
The accuracy of K Nearest Neighbor Algorithm is: 77.21788502484031 %
The accuracy of Random Forest Algorithm is: 79.347054648687 %


In [ ]:
# Hence, we conclude that Logistic regression is best suited for this dataset.